# Generated by Django 4.2 on 2024-06-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flan',
            name='image_url',
        ),
        migrations.AddField(
            model_name='flan',
            name='image',
            field=models.ImageField(default='flans/default.jpg', upload_to='flans/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flan',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
